// Complete mock recipe details for individual recipes
export const mockRecipeDetails = {
  "52874": {
    idMeal: "52874",
    strMeal: "Beef and Mustard Pie",
    strMealThumb: "https://www.themealdb.com/images/media/meals/sytuq1511463245.jpg",
    strCategory: "Beef",
    strArea: "British",
    strInstructions: "Preheat your oven to 200°C/180°C Fan/Gas Mark 6.\nRoll out the pastry on a lightly floured surface and use it to line a 20cm/8in loose-bottomed tart tin. Trim the edges, then line the pastry case with baking parchment and fill with baking beans. Bake blind for 15 minutes, then remove the beans and parchment and bake for a further 5 minutes until lightly golden.\nMeanwhile, heat the oil in a large frying pan, add the onions and cook gently for 10-15 minutes until softened and lightly golden. Add the garlic and cook for 1 minute more.\nAdd the beef to the pan and cook over a high heat until browned all over. Stir in the flour and cook for 1 minute, then gradually add the stock and mustard, stirring constantly. Bring to the boil, then reduce the heat and simmer for 20 minutes until the sauce has thickened.\nRemove the pastry case from the oven and reduce the oven temperature to 180°C/160°C Fan/Gas Mark 4. Pour the beef mixture into the pastry case.\nRoll out the remaining pastry to make a lid for the pie. Use a fork to press the edges together and trim off any excess. Cut a small hole in the centre of the pie to allow steam to escape.\nBrush the top of the pie with beaten egg and bake for 25-30 minutes until golden brown and piping hot.",
    strIngredient1: "Beef",
    strIngredient2: "Onions",
    strIngredient3: "Garlic",
    strIngredient4: "Flour",
    strIngredient5: "Beef Stock",
    strIngredient6: "Mustard",
    strIngredient7: "Pastry",
    strIngredient8: "Egg",
    strIngredient9: "Oil",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "500g",
    strMeasure2: "2 large",
    strMeasure3: "2 cloves",
    strMeasure4: "2 tbsp",
    strMeasure5: "300ml",
    strMeasure6: "2 tbsp",
    strMeasure7: "500g",
    strMeasure8: "1 beaten",
    strMeasure9: "2 tbsp",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strYoutube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  },
  "52878": {
    idMeal: "52878",
    strMeal: "Beef and Oyster pie",
    strMealThumb: "https://www.themealdb.com/images/media/meals/vxtqtx1511463740.jpg",
    strCategory: "Beef",
    strArea: "British",
    strInstructions: "Heat the oil in a large pan and brown the beef in batches. Remove from the pan and set aside.\nAdd the onions to the pan and cook until softened. Add the garlic and cook for 1 minute.\nReturn the beef to the pan along with the mushrooms, thyme, and bay leaves. Pour in the beef stock and bring to a simmer. Cover and cook for 2 hours until the beef is tender.\nRemove the bay leaves and stir in the oysters. Season with salt and pepper.\nSpoon the mixture into a pie dish and top with the pastry. Brush with beaten egg and bake at 200°C for 30 minutes until golden.",
    strIngredient1: "Beef",
    strIngredient2: "Onions",
    strIngredient3: "Garlic",
    strIngredient4: "Mushrooms",
    strIngredient5: "Thyme",
    strIngredient6: "Bay Leaves",
    strIngredient7: "Beef Stock",
    strIngredient8: "Oysters",
    strIngredient9: "Pastry",
    strIngredient10: "Egg",
    strIngredient11: "Oil",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1kg",
    strMeasure2: "2 large",
    strMeasure3: "3 cloves",
    strMeasure4: "200g",
    strMeasure5: "2 sprigs",
    strMeasure6: "2",
    strMeasure7: "500ml",
    strMeasure8: "12",
    strMeasure9: "500g",
    strMeasure10: "1 beaten",
    strMeasure11: "2 tbsp",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strYoutube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  },
  "52767": {
    idMeal: "52767",
    strMeal: "Beef Bourguignon",
    strMealThumb: "https://www.themealdb.com/images/media/meals/vtqxtu1511464183.jpg",
    strCategory: "Beef",
    strArea: "French",
    strInstructions: "Heat the oil in a large casserole dish and brown the beef in batches. Remove from the dish and set aside.\nAdd the onions to the dish and cook until softened. Add the garlic and cook for 1 minute.\nReturn the beef to the dish along with the bacon, carrots, and mushrooms. Stir in the flour and cook for 1 minute.\nAdd the wine, stock, and tomato purée. Bring to a simmer, then cover and cook in the oven at 160°C for 2-3 hours until the beef is tender.\nSeason with salt and pepper and serve with crusty bread or potatoes.",
    strIngredient1: "Beef",
    strIngredient2: "Onions",
    strIngredient3: "Garlic",
    strIngredient4: "Bacon",
    strIngredient5: "Carrots",
    strIngredient6: "Mushrooms",
    strIngredient7: "Flour",
    strIngredient8: "Red Wine",
    strIngredient9: "Beef Stock",
    strIngredient10: "Tomato Purée",
    strIngredient11: "Oil",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1.5kg",
    strMeasure2: "2 large",
    strMeasure3: "4 cloves",
    strMeasure4: "200g",
    strMeasure5: "2 large",
    strMeasure6: "200g",
    strMeasure7: "2 tbsp",
    strMeasure8: "750ml",
    strMeasure9: "500ml",
    strMeasure10: "2 tbsp",
    strMeasure11: "2 tbsp",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strYoutube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  },
  "53043": {
    idMeal: "53043",
    strMeal: "Chicken & mushroom Hotpot",
    strMealThumb: "https://www.themealdb.com/images/media/meals/uyqrrv1511553350.jpg",
    strCategory: "Chicken",
    strArea: "British",
    strInstructions: "Heat the oil in a large pan and brown the chicken pieces. Remove from the pan and set aside.\nAdd the onions to the pan and cook until softened. Add the garlic and mushrooms and cook for 5 minutes.\nStir in the flour and cook for 1 minute, then gradually add the stock and cream, stirring constantly. Bring to a simmer.\nReturn the chicken to the pan along with the thyme. Season with salt and pepper.\nTransfer to an ovenproof dish and top with the sliced potatoes. Brush with melted butter and bake at 180°C for 45-50 minutes until golden and bubbling.",
    strIngredient1: "Chicken",
    strIngredient2: "Onions",
    strIngredient3: "Garlic",
    strIngredient4: "Mushrooms",
    strIngredient5: "Flour",
    strIngredient6: "Chicken Stock",
    strIngredient7: "Cream",
    strIngredient8: "Thyme",
    strIngredient9: "Potatoes",
    strIngredient10: "Butter",
    strIngredient11: "Oil",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1kg",
    strMeasure2: "2 large",
    strMeasure3: "3 cloves",
    strMeasure4: "300g",
    strMeasure5: "2 tbsp",
    strMeasure6: "500ml",
    strMeasure7: "200ml",
    strMeasure8: "2 sprigs",
    strMeasure9: "4 large",
    strMeasure10: "50g",
    strMeasure11: "2 tbsp",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strYoutube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  },
  "52875": {
    idMeal: "52875",
    strMeal: "Chicken Alfredo Pasta",
    strMealThumb: "https://www.themealdb.com/images/media/meals/8nxxf81527374744.jpg",
    strCategory: "Chicken",
    strArea: "Italian",
    strInstructions: "Cook the pasta according to package instructions. Drain and set aside.\nSeason the chicken with salt and pepper. Heat the oil in a large pan and cook the chicken until golden and cooked through. Remove from the pan.\nAdd the butter to the pan and melt. Add the garlic and cook for 1 minute. Add the cream and bring to a simmer.\nStir in the Parmesan cheese and season with salt and pepper. Return the chicken to the pan.\nAdd the cooked pasta and toss to combine. Serve immediately with extra Parmesan cheese.",
    strIngredient1: "Chicken",
    strIngredient2: "Pasta",
    strIngredient3: "Butter",
    strIngredient4: "Garlic",
    strIngredient5: "Cream",
    strIngredient6: "Parmesan Cheese",
    strIngredient7: "Oil",
    strIngredient8: "Salt",
    strIngredient9: "Pepper",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "500g",
    strMeasure2: "400g",
    strMeasure3: "50g",
    strMeasure4: "3 cloves",
    strMeasure5: "300ml",
    strMeasure6: "100g",
    strMeasure7: "2 tbsp",
    strMeasure8: "to taste",
    strMeasure9: "to taste",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strYoutube: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
  }
};
